src/accounts/models.py
from datetime import datetime

from flask_login import UserMixin

from src import bcrypt, db


class User(UserMixin, db.Model):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String, unique=True, nullable=False)
    password = db.Column(db.String, nullable=False)
    created_on = db.Column(db.DateTime, nullable=False)
    is_admin = db.Column(db.Boolean, nullable=False, default=False)

    def __init__(self, email, password, is_admin=False):
        self.email = email
        self.password = bcrypt.generate_password_hash(password)
        self.created_on = datetime.now()
        self.is_admin = is_admin

    def __repr__(self):
        return f"<email {self.email}>"

src/accounts/forms.py
from flask_wtf import FlaskForm
from wtforms import EmailField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from src.accounts.models import User


class LoginForm(FlaskForm):
    email = EmailField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])


class RegisterForm(FlaskForm):
    email = EmailField(
        "Email", validators=[DataRequired(), Email(message=None), Length(min=6, max=40)]
    )
    password = PasswordField(
        "Password", validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        "Repeat password",
        validators=[
            DataRequired(),
            EqualTo("password", message="Passwords must match."),
        ],
    )

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        if self.password.data != self.confirm.data:
            self.password.errors.append("Passwords must match")
            return False
        return True

src/__init__.py
from decouple import config
from flask import Flask, render_template
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from src.dicom_processor.views import dicom_processor_bp

app = Flask(__name__)
app.config.from_object(config("APP_SETTINGS"))
app.config.from_object('config.Config')



login_manager = LoginManager()
login_manager.init_app(app)
bcrypt = Bcrypt(app)
db = SQLAlchemy(app)
migrate = Migrate(app, db)

# Registering blueprints
from src.accounts.views import accounts_bp
from src.core.views import core_bp

app.register_blueprint(accounts_bp)
app.register_blueprint(core_bp)
app.register_blueprint(dicom_processor_bp, url_prefix='/dicom')

from src.accounts.models import User

login_manager.login_view = "accounts.login"
login_manager.login_message_category = "danger"


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()


########################
#### error handlers ####
########################


@app.errorhandler(401)
def unauthorized_page(error):
    return render_template("errors/401.html"), 401


@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404


@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500

src/accounts/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required, login_user, logout_user, current_user

from src import bcrypt, db
from src.accounts.models import User

from .forms import LoginForm, RegisterForm

accounts_bp = Blueprint("accounts", __name__)


@accounts_bp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        flash("You are already registered.", "info")
        return redirect(url_for("core.home"))
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(email=form.email.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()

        login_user(user)
        flash("You registered and are now logged in. Welcome!", "success")

        return redirect(url_for("core.home"))
 
    return render_template("accounts/register.html", form=form)


@accounts_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        flash("You are already logged in.", "info")
        return redirect(url_for("dicom_processor.upload"))
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, request.form["password"]):
            login_user(user)
            return redirect(url_for("dicom_processor.upload"))
        else:
            flash("Invalid email and/or password.", "danger")
            return render_template("accounts/login.html", form=form)
    return render_template("accounts/login.html", form=form)


@accounts_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You were logged out.", "success")
    return redirect(url_for("core.home"))

src/core/views.py
from flask import Blueprint, render_template
from flask_login import login_required

core_bp = Blueprint("core", __name__)

@core_bp.route("/")
def home():
    return render_template("core/index.html")

# Add a route for the predict window
@core_bp.route("/upload")
@login_required
def predict():
    # Assuming you have a template for the predict window named "predict.html"
    return render_template("core/predict.html")

src/dicom_processor/views.py
import os
from flask import Blueprint, request, current_app, redirect, url_for, render_template, flash, Response
from werkzeug.utils import secure_filename
from sybil import Serie, Sybil
from flask_login import login_required
from flask import session
import csv
from io import StringIO

dicom_processor_bp = Blueprint('dicom_processor', __name__)
model = Sybil("sybil_base")

@dicom_processor_bp.route('/upload', methods=['GET', 'POST'])
@login_required
def upload():
    if request.method == 'POST':
        user_name = request.form.get('user_name')
        files = request.files.getlist('dicom_files')  # Change to getlist to handle multiple files
        
        if not files or files[0].filename == '':
            flash('No selected file', "danger")
            return redirect(request.url)
        
        dicom_paths = []
        for file in files:
            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                filepath = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
                file.save(filepath)
                dicom_paths.append(filepath)
        
        if dicom_paths:
            serie = Serie(dicom_paths)
            scores = model.predict([serie])
            values_list = [value for sublist in scores.scores for value in sublist]
            scores_percentage = [round(score * 100, 2) for score in values_list]
            session['scores'] = scores_percentage
            session['user_name'] = secure_filename(user_name)
            clear_upload_folder()
            return render_template('dicom_processor/results.html', user_name=user_name, scores=scores_percentage)
        else:
            flash('No valid files uploaded', "danger")
            return redirect(request.url)
    return render_template('dicom_processor/upload.html')


@dicom_processor_bp.route('/download_csv')
@login_required
def download_csv():
    # Retrieve the scores from session
    scores_percentage = session.get('scores', [])
    user_name = session.get('user_name', 'scores') 
    if not scores_percentage:
        flash("No scores to download.")
        return redirect(url_for('dicom_processor.upload'))

    si = StringIO()
    cw = csv.writer(si)
    cw.writerow(['Xecan Cancer Prediction Percentage (%)'])  # Header row
    for score in scores_percentage:
        cw.writerow([score])

    output = si.getvalue()
    si.close()

    filename = f"{user_name}_prediction.csv"
    return Response(
        output,
        mimetype="text/csv",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )



def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() == 'dcm'


def clear_upload_folder(upload_folder_path="./uploads"):
    for filename in os.listdir(upload_folder_path):
        file_path = os.path.join(upload_folder_path, filename)
        try:
            if os.path.isfile(file_path) or os.path.islink(file_path):
                os.unlink(file_path)
            elif os.path.isdir(file_path):
                pass
        except Exception as e:
            print(f'Failed to delete {file_path}. Reason: {e}')

src/templates/dicom_processor/results.html
{% extends "_base.html" %}

{% block content %}

<style>
    .centered-text {
        text-align: center;
        margin-bottom: 20px; /* Adds space below the heading */
    }
    .button-group {
        display: flex;
        justify-content: center;
        gap: 20px; /* Adds space between buttons */
        margin-bottom: 15px; /* Adds space below the buttons */
    }
    table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px; /* Adds space above the buttons */
    }
    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: center; /* Ensures text is centered within the cells */
    }
    th {
        background-color: #0d6efd;
        color: white;
    }
    .btn {
        padding: 10px 10px;
        text-decoration: none;
        border-radius: 4px;
    }
    .btn-primary {
        background-color: #0d6efd;
        color: white;
    }
    .btn-primary:hover {
        background-color: #0d6efd;
    }
    .btn-secondary {
        background-color: #6c757d;
        color: white;
    }
    .btn-secondary:hover {
        background-color: #5a6268;
    }
</style>

<div class="centered-text">
    <br>
    <h2>XECAN Lung Cancer Risk Prediction</h2>
</div>
<table>
    <tr>
        <th>Patient Name</th>
        <th>Years</th>
        <th>1 year</th>
        <th>2 years</th>
        <th>3 years</th>
        <th>4 years</th>
        <th>5 years</th>
        <th>6 years</th>
    </tr>
    <tr>
        <td>{{ user_name }}</td>
        <td>Predicted Risk Percentage</td>
        {% for score in scores %}
        <td>{{ score }}%</td>
        {% endfor %}
    </tr>
    <!-- Add more rows for additional patients if needed -->
</table>
<br>
<div class="button-group">
    <a href="{{ url_for('dicom_processor.download_csv') }}" class="btn btn-primary">Download CSV</a>
    <!-- Button to predict another -->
    <a href="{{ url_for('dicom_processor.upload') }}" class="btn btn-primary">Predict Another</a>
</div>

{% endblock %}

src/templates/dicom_processor/upload.html
{% extends "_base.html" %}
{% block content %}
<style>
    .container_upload {
        max-width: 750px;
        margin: 0 auto;
        padding: 20px;
        text-align: center;
    }
    .upload-instructions {
        margin-top: 20px;
        font-size: 20px; /* Increased font size */
        margin-bottom: 30px; /* Increased spacing */
    }
    .file-input-container {
        margin: 20px 0;
    }
    .file-input-button {
        background-color: #0d6efd;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px; /* You can adjust the size as needed */
        text-align: center;
        display: inline-block;
    }
    .file-input-button:hover {
        background-color: #0d6efd;
    }
    .file-list-container {
        border: 2px solid #ccc;
        padding: 10px;
        margin: 20px 0;
        height: 200px; /* Increased height */
        overflow-y: auto;
    }
    .submit-button {
        background-color: #0d6efd;
        color: white;
        padding: 10px 20px; /* Adjusted padding for a larger button */
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px; /* Larger font size for the button text */
        margin-top: 15px;
    }
    .submit-button:hover {
        background-color: #0d6efd;
    }

    .loader {
    position: absolute;
    left: 50%;
    top: 80%;
    z-index: 1;
    margin: -76px 0 0 -76px;
    border: 16px solid #504c4c98; 
    border-top: 16px solid #0d6efd; 
    border-radius: 50%;
    width: 120px;
    height: 120px;
    animation: spin 2s linear infinite;
    display: none;
    }

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
</style>

<div class="container_upload">
    <h1>XECAN LDCT AI Predict Interface</h1>
    <p class="upload-instructions">The model expects the input to be an Axial LDCT, where the first frame is of the abdominal region and the last frame is along the clavicles. The model only accepts dicom files.</p>
    <form method="post" enctype="multipart/form-data" action="{{ url_for('dicom_processor.upload') }}">

        <!-- Add a field for the name of the user -->
        <div class="input-group mb-3">
            <span class="input-group-text" id="inputGroup-sizing-default">Patient Name</span>
            <input type="text" name="user_name" class="form-control" aria-label="Name" aria-describedby="inputGroup-sizing-default" required placeholder="Enter name">
        </div>    

        <div class="file-input-container">
            <label for="dicom_file" class="file-input-button">Choose File</label>
            <input type="file" name="dicom_files" id="dicom_file" accept=".dcm" multiple hidden/>
        </div>
        <div id="file-list" class="file-list-container">
            <!-- JavaScript will populate this area with the list of chosen files -->
        </div>
        <input type="submit"  id="submit-button" class="submit-button" value="  Predict  ">
        <div id="loader" class="loader"></div>
        <br>
        <br>
        <br>
        <br>
        <br>
    </form>
</div>
<script>
    // JavaScript to update the list of files when files are chosen
    document.getElementById('dicom_file').addEventListener('change', function() {
        var fileListContainer = document.getElementById('file-list');
        fileListContainer.innerHTML = ''; // Clear the list container
        for (var i = 0; i < this.files.length; i++) {
            fileListContainer.innerHTML += this.files[i].name + '<br>';
        }
    });

    document.getElementById('submit-button').addEventListener('click', function() {
        // Display the loader
        document.getElementById('loader').style.display = 'block';
        
        // Prevent the default form submission if needed
        // event.preventDefault();
    });

</script>
{% endblock %}